### ISSUE TITLE
패키지 정리 통일

### ISSUE THREAD

**Issue by syxxn** [EntryDSM/Yapaghetti#175]
## 개요
지금 config를 모아두지 않고 각 패키지에서 설정하는 걸로 알고 있습니다.
예를 들어 security config 같은 경우 ...>security>SecurityConfig.java로 있고,
annotaion에 대한 config는 ...>annotaion>config>GlobalComponentScan.java로 있는데요,
filterConfig는 config에 대한 config가 아닌데 왜 config 패키지에 있는건가요?
다른 패키지와 통일시키자면 ...>filter>FilterConfig.java로 있는 것이 정확하지 않을까요?

다른 Config는 ~~Config인데 왜 어노테이션에 대한 Configuration 클래스명은 GlobalComponentScan인가요?

## 작업 내용
- [ ] 패키지 구조  통일
- [ ] 클래스명 통일

## 참고사항
* [https://github.com/EntryDSM/Yapaghetti/blob/main/yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/config/FilterConfig.java](https://github.com/EntryDSM/Yapaghetti/blob/main/yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/config/FilterConfig.java)
* [https://github.com/EntryDSM/Yapaghetti/blob/main/yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/annotation/config/GlobalComponentScan.java](https://github.com/EntryDSM/Yapaghetti/blob/main/yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/annotation/config/GlobalComponentScan.java)

**Comment by eogus2513** [comment]
또 저희 infra안에 infra가 있는데 그것도 global과 같은 레벨에 두는 게 어떤가요?
