### ISSUE TITLE
회사 생성 / 수정 버그

### ISSUE THREAD

**Issue by osangu** [EntryDSM/Yapaghetti#206]
### 개요
> 회사 생성과 업데이트를 하려고 할 때 발생하는 에러입니다.

### 찾아본 url 들입니다.
https://kongpowder.tistory.com/87  
https://okky.kr/articles/720876   
https://velog.io/@tkaqhcjstk/spring-org.springframework.web.util.NestedServletException-Request-processing-failed-nested-exception-is-org.springframework.dao.DuplicateKeyException-%EC%98%A4%EB%A5%98%ED%95%B4%EA%B2%B0

<img width="1379" alt="스크린샷 2022-08-30 오후 8 30 27" src="https://user-images.githubusercontent.com/80697064/187425818-641ca1e5-449b-4264-82a8-f62d25404d0e.png">

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.dao.InvalidDataAccessApiUsageException: detached entity passed to persist: kr.hs.entrydsm.yapaghetti.domain.user.persistence.entity.UserEntity; nested exception is org.hibernate.PersistentObjectException: detached entity passed to persist: kr.hs.entrydsm.yapaghetti.domain.user.persistence.entity.UserEntity

**Comment by eogus2513** [comment]
@osangu 이거 버그 해결했는데 내가 PR 올려도 됨?
